### ISSUE TITLE
配置resolve alias有问题

### ISSUE THREAD

**Issue by WarrenJones** [keenwon/Egg-Webpack-Starter#1]
随便配置一个别名，会找不到对应路径

**Comment by keenwon** [comment]
alias 有两处：

- https://github.com/keenwon/Egg-Webpack-Starter/blob/master/client/build/webpack.common.js#L9
- https://github.com/keenwon/Egg-Webpack-Starter/blob/master/babel.config.js#L36

可以考虑合并到一处，babel 应该有此类插件

**Comment by WarrenJones** [comment]
解决了，是我自己tsconfig的问题，感谢

**Comment by MJingv** [comment]
js resolve alias有问题
``` 
ERROR in ./client/src/views/Home.jsx
Module not found: Error: Can't resolve '../../../src/common/services/ajax.js' in '/Users/pri/wc-fe/client/src/views'
```

@keenwon 大佬能帮忙看看嘛
