### ISSUE TITLE
ctx的configh和helper是undefined

### ISSUE THREAD

**Issue by MJingv** [keenwon/Egg-Webpack-Starter#4]
是内部做了什么逻辑吗？ctx的config和helper是undefined

![d](https://pt-starimg.didistatic.com/static/starimg/img/GHqynDvpb81577439072072.png)

**Comment by keenwon** [comment]
截图只能说明 errors 是 undefined

**Comment by MJingv** [comment]
> 截图只能说明 errors 是 undefined

![](https://pt-starimg.didistatic.com/static/starimg/img/JK7E82tNf31577441238124.png)
![](https://pt-starimg.didistatic.com/static/starimg/img/dMh2vtk3xV1577441237260.png)
![](https://pt-starimg.didistatic.com/static/starimg/img/skZvn5myx61577441237037.png)

**Comment by keenwon** [comment]
config 不是这么定义的，看下 egg 文档

**Comment by MJingv** [comment]
> config 不是这么定义的，看下 egg 文档

好的，我再看看，helper为什么没有呢？

**Comment by MJingv** [comment]
> > config 不是这么定义的，看下 egg 文档
> 
> 好的，我再看看，helper为什么没有呢？

/extend/helper 在ctx.helper里没有

**Comment by MJingv** [comment]
helper可以找到，自己的问题
